name: pr-merge-CD

on:
  push:
    branches: main

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          check-latest: true

      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Install gh-pages
        run: yarn add gh-pages -D

      - name: Build vuepress
        run: yarn docs:build

      - name: Deploy to gh-pages
        run: npx gh-pages -d ../docs/.vuepress/dist

      - name: Remove gh-pages
        run: yarn remove gh-pages

      # - name: Upload to Deploy Server
      #   uses: easingthemes/ssh-deploy@v2.0.7
      #   env:
      #     # SSH_PRIVATE_KEY为准备工作步骤三中生成密钥对里的私钥
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_TOKEN }}
      #     # 指定当前目录中要上传的内容
      #     SOURCE: "dist/"
      #     # 指定上传到部署机器的哪个目录下
      #     TARGET: "/data/www"
      #     # 上传前指令，此处用于清空TARGET下的文件
      #     ARGS: "-avzr --delete"
      #     # REMOTE_HOST为机器的公网IP
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     # REMOTE_USER为登录机器时用到账号名
      #     REMOTE_USER: ${{secrets.REMOTE_USER}}
